# Generated by Django 5.0.2 on 2024-06-29 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPredictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=100)),
                ('Customer_Type', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Type_of_Travel', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('Inflight_wifi_service', models.IntegerField()),
                ('Food_and_drink', models.IntegerField()),
                ('Online_boarding', models.IntegerField()),
                ('Seat_comfort', models.IntegerField()),
                ('Inflight_entertainment', models.IntegerField()),
                ('Onboard_service', models.IntegerField()),
                ('Leg_room_service', models.IntegerField()),
                ('Baggage_handling', models.IntegerField()),
                ('Checkin_service', models.IntegerField()),
                ('Inflight_service', models.IntegerField()),
                ('Cleanliness', models.IntegerField()),
                ('Departure_Delay_in_Minutes', models.IntegerField()),
                ('satisfaction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
